#把该文件复制到 <已经编译好的> linux安装包目录下 <与install.sh脚本在同一层级> ，执行以下命令完成docker镜像打包，最后推送和分发到docker hub中~
# docker build -t taycc/gomessage:1.0.7         #这个镜像是指定版本上传
# docker build -t taycc/gomessage:latest        #这个镜像是覆盖latest上传

FROM golang:1.15.15-alpine

RUN mkdir -p /opt/gomessage && rm -rf /opt/gomessage/*

WORKDIR /opt/gomessage

ADD ./gomessage.tar.gz /opt/gomessage/

EXPOSE 7077

ENTRYPOINT ["/opt/gomessage/gomessage"]