swagger: "2.0"
info:
  title: GoMessage
  description: 转发Json格式的信息，到钉钉、微信、或其它客户端
  version: v1
  contact:
    email: tay3223@qq.com
basePath: /v1
paths:
  /alertmanager/dingding/k8s:
    post:
      tags:
      - alertmanager
      description: 推送数据到钉钉，数据来自于Alertmanager的webhook推送
      operationId: K8sControllers.推送数据
      responses:
        "200":
          description: ok
  /alertmanager/dingding/linux:
    post:
      tags:
      - alertmanager
      description: 推送数据到钉钉，数据来自于Alertmanager的webhook推送
      operationId: LinuxControllers.推送数据
      responses:
        "200":
          description: ok
  /test/:
    get:
      tags:
      - test
    post:
      tags:
      - test
  /web/client:
    get:
      tags:
      - web
    post:
      tags:
      - web
  /web/client/{id}:
    get:
      tags:
      - web
    delete:
      tags:
      - web
  /web/client/active:
    put:
      tags:
      - web
  /web/json:
    get:
      tags:
      - web
      description: 劫持到过境数据
      operationId: JsonControllers./v1/web/json
      responses:
        "200":
          description: 响应成功
        "404":
          description: 错误请求
  /web/map:
    get:
      tags:
      - web
      description: 获取用户变量
      operationId: MapControllers./v1/web/map
      responses:
        "200":
          description: 响应成功
        "404":
          description: 错误请求
    post:
      tags:
      - web
      description: 更新用户变量
      operationId: MapControllers./v1/web/map
      parameters:
      - in: body
        name: key_value_list
        description: 存放用户变量的一个list
        schema:
          type: string
        type: string
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.Configmap'
        "404":
          description: 错误请求
  /web/template:
    get:
      tags:
      - web
      description: Get user template
      operationId: TemplateControllers.Get user template
      responses:
        "200":
          description: 响应成功
        "404":
          description: 错误请求
    post:
      tags:
      - web
      description: 添加用户模板
      operationId: TemplateControllers./v1/web/template
      responses:
        "200":
          description: 响应成功
        "404":
          description: 错误请求
definitions:
  models.Configmap:
    title: Configmap
    type: object
    properties:
      CreateTime:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      Key:
        type: string
      UpdateTime:
        type: string
        format: datetime
      Value:
        type: string
tags:
- name: alertmanager
  description: |
    Prometheus相关api
- name: test
  description: |
    测试api
- name: web
  description: |
    GoMessage前后端交互api
- name: web
  description: |
    控制器：用户变量功能
- name: web
  description: |
    控制器：用户消息体的模板
- name: web
  description: |
    client api 相关的控制器
- name: web
  description: |
    单个client客户端操作的控制器
- name: web
  description: |
    激活状态的控制器
