---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomessage
  namespace: default
  labels:
    app: gomessage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomessage
  template:
    metadata:
      labels:
        app: gomessage
    spec:
      containers:
        - name: gomessage
          image: "docker.io/gomessage/gomessage:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 7077
          volumeMounts:
            - name: gomessage-data
              mountPath: /opt/gomessage/data
      volumes:
        - name: gomessage-data
          persistentVolumeClaim:
            claimName: gomessage-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gomessage-pvc
  namespace: default
  labels:
    app: gomessage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gomessage-svc
  namespace: default
  labels:
    app: gomessage
spec:
  selector:
    app: gomessage
  type: NodePort
  ports:
    - port: 80
      targetPort: 7077
      name: gomessage
      nodePort: 32077
