---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: default
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.io/gomessage/gomessage:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: version
              value: {{ .Chart.AppVersion }}
          volumeMounts:
            - name: {{ .Chart.Name }}-data
              mountPath: /opt/gomessage/data
      volumes:
        - name: {{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
